spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: Simon
    password: 123456
    url: jdbc:mysql://localhost:3306/advancedDB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: adb_pro
      #uri: mongodb+srv://user:1q2w3e4r5t@adb-shard-00-00-iyiwl.mongodb.net:27017/adbproj
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl