
spring:
  data:
    mongodb:
      uri: mongodb+srv://user:1q2w3e4r5t@adb-iyiwl.mongodb.net/adbproj

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql021496.
    url: jdbc:mysql://localhost:3306/QAtest?serverTimezone=UTC
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl